### ISSUE TITLE
Delete storyboard step by showing an icon to delete as a popup menu (on selection)

### ISSUE THREAD

**Issue by duquevieira** [duquevieira/AdventureCreator#171]
![Image](https://github.com/duquevieira/AdventureCreator/assets/25690501/4566b6eb-75ef-4513-8367-5625b65a0184)

**Comment by DuarteFGuerreiro** [comment]
![Image](https://github.com/duquevieira/AdventureCreator/assets/72998351/827bbeb2-a3eb-45eb-926b-f9cd3aa08d92)
